### ISSUE TITLE
GODOT ERROR: Error while loading file 'main.tscn'

### ISSUE THREAD

**Issue by housaynraffea** [ic3bug/FPC#2]
I get this error when I try to load the main scene. What happened here? Is the scene corrupted? Because IIRC, There was supposed to be an exported blender file acting as the map, but it's missing now. I may be completely wrong. I could just make a new scene and place the player there, but I just wanted to know why this happens in the first place.

**Comment by nezvers** [comment]
@housaynraffea You need to enter blender directory for the Godot editor.
